# Generated by Django 4.1.3 on 2022-11-22 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('in_stock', models.IntegerField(default=0)),
                ('descr', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('picture', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'books',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('order_date', models.DateField()),
                ('pay_date', models.DateField()),
                ('deliv_date', models.DateField()),
                ('state', models.CharField(max_length=10)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.user')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
    ]
